name: nyumba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Adjust the range based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  local_auth: ^2.2.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0  # Ensure this is added
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.0.20 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/house_logo.png
    - lib/assets/lang/sw.json
    - lib/assets/lang/en.json
